/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Panels.PanelZBuffer;
import java.awt.Color;
import java.awt.image.BufferedImage;

/**
 * Janela do ZBuffer
 * @author Mateus
 */
public class ZBuffer extends javax.swing.JFrame {

    /**
     * Creates new form ZBuffer
     */
    BufferedImage zbuffer;
    PanelZBuffer zb;

    public ZBuffer(BufferedImage c, int largura, int altura) {
        initComponents();
        this.setSize(largura, altura);
        zbuffer = c;
        if (zb == null) {
            zb = new PanelZBuffer(zbuffer);
        }
        zb.setSize(largura, altura);
        this.panelZBuffer.add(zb);
    }

    public PanelZBuffer getZb() {
        return zb;
    }

    public void setZbuffer(BufferedImage zbuffer, int largura, int altura) {
        this.zbuffer = zbuffer;
        if (zb == null) {
            zb = new PanelZBuffer(zbuffer);
        } else {
            zb.setMatriz(zbuffer);
        }
        zb.setSize(largura, altura);
        this.panelZBuffer.add(zb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelZBuffer = new javax.swing.JPanel();

        javax.swing.GroupLayout panelZBufferLayout = new javax.swing.GroupLayout(panelZBuffer);
        panelZBuffer.setLayout(panelZBufferLayout);
        panelZBufferLayout.setHorizontalGroup(
            panelZBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        panelZBufferLayout.setVerticalGroup(
            panelZBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelZBuffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelZBuffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelZBuffer;
    // End of variables declaration//GEN-END:variables
}
